spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://124.71.31.245:35432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:4Y7RJEM2LJfTnShW}
  data:
    redis:
      host: ${REDIS_HOST:124.71.31.245}
      port: ${REDIS_PORT:26739}
      password: ${REDIS_PASSWORD:rpbiSFjfKHyWXhxf}

logging:
  level:
    com.stableflow: DEBUG
